---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: end-of-file-fixer
        description: Ensures that files end with a newline
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ["--maxkb=6000"]
        description: Prevents the addition of large files to the repository
      - id: no-commit-to-branch
        args: [--branch, main]
        description: Prevents pushes directly to main branch
      - id: check-json
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
